//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameManager.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameNotStartedException", Namespace="http://schemas.datacontract.org/2004/07/GameService")]
    [System.SerializableAttribute()]
    public partial class GameNotStartedException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGameManager")]
    public interface IGameManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/StartGame", ReplyAction="http://tempuri.org/IGameManager/StartGameResponse")]
        void StartGame(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/EndGame", ReplyAction="http://tempuri.org/IGameManager/EndGameResponse")]
        void EndGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SetAdv", ReplyAction="http://tempuri.org/IGameManager/SetAdvResponse")]
        void SetAdv(string adv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagerChannel : GameManager.ServiceReference1.IGameManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameManagerClient : System.ServiceModel.ClientBase<GameManager.ServiceReference1.IGameManager>, GameManager.ServiceReference1.IGameManager {
        
        public GameManagerClient() {
        }
        
        public GameManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartGame(int n1, int n2) {
            base.Channel.StartGame(n1, n2);
        }
        
        public void EndGame() {
            base.Channel.EndGame();
        }
        
        public void SetAdv(string adv) {
            base.Channel.SetAdv(adv);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Silverlight", ConfigurationName="ServiceReference1.IGamePlayer", CallbackContract=typeof(GameManager.ServiceReference1.IGamePlayerCallback))]
    public interface IGamePlayer {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="Silverlight/IGamePlayer/MakeMove", ReplyAction="Silverlight/IGamePlayer/MakeMoveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GameManager.ServiceReference1.GameNotStartedException), Action="Silverlight/IGamePlayer/MakeMoveGameNotStartedExceptionFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="GameNotStartedException", Namespace="http://schemas.datacontract.org/2004/07/GameService")]
        string MakeMove(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="Silverlight/IGamePlayer/JoinGame", ReplyAction="Silverlight/IGamePlayer/JoinGameResponse")]
        void JoinGame(string name, string language);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="Silverlight/IGamePlayer/ExitGame", ReplyAction="Silverlight/IGamePlayer/ExitGameResponse")]
        void ExitGame();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGamePlayerCallback {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="Silverlight/IGamePlayer/NewAnnounce", ReplyAction="Silverlight/IGamePlayer/NewAnnounceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<string>), Action="Silverlight/IGamePlayer/NewAnnounceFaultExceptionOf_StringFault", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Name="FaultExceptionOfstring", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        string NewAnnounce(string msg, int ex);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="Silverlight/IGamePlayer/NewAdvertisement", ReplyAction="Silverlight/IGamePlayer/NewAdvertisementResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<string>), Action="Silverlight/IGamePlayer/NewAdvertisementFaultExceptionOf_StringFault", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Name="FaultExceptionOfstring", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        string NewAdvertisement(string msg, int ex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGamePlayerChannel : GameManager.ServiceReference1.IGamePlayer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GamePlayerClient : System.ServiceModel.DuplexClientBase<GameManager.ServiceReference1.IGamePlayer>, GameManager.ServiceReference1.IGamePlayer {
        
        public GamePlayerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GamePlayerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GamePlayerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GamePlayerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GamePlayerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string MakeMove(int n1, int n2) {
            return base.Channel.MakeMove(n1, n2);
        }
        
        public void JoinGame(string name, string language) {
            base.Channel.JoinGame(name, language);
        }
        
        public void ExitGame() {
            base.Channel.ExitGame();
        }
    }
}
